### ISSUE TITLE
Examples don't work with newest version of Nim

### ISSUE THREAD

**Issue by YafahEdelman** [akiradeveloper/nim-fuse#5]
As of now the examples throw:

> Error:  execution of an external program failed; rerun with --parallelBuild:1 to see the error message

When run with that option: 

> gcc: error: Package: No such file or directory
> gcc: error: fuse: No such file or directory
> gcc: error: was: No such file or directory
> gcc: error: not: No such file or directory
> gcc: error: found: No such file or directory
> gcc: error: in: No such file or directory
> gcc: error: the: No such file or directory
> gcc: error: pkg-config: No such file or directory
> gcc: error: search: No such file or directory
> gcc: error: path.: No such file or directory
> gcc: fatal error: no input files
> compilation terminated.
> sh: 4: Syntax error: EOF in backquote substitution

**Comment by akiradeveloper** [comment]
I think you need to set up your environment first.
- What OS are you using?  
- What example are you trying?  
- Did you see that example work before?

To check, I reran the CI and confirmed sample works for both master (0.10.2) and devel in Linux.

https://travis-ci.org/akiradeveloper/nim-fuse/builds/51688337

**Comment by YafahEdelman** [comment]
I'm using Ubuntu 14.04, and I tried both the hello and hello_hi examples. Any idea what I would need to do to set up my environment for it too work?  Thanks for the help.

In order to run it I'm just running: `nim c --run hello.nim`. Are there arguments I need to pass?

**Comment by akiradeveloper** [comment]
The .travis.yml file would help you. It sets up environment from scratch and succeeds running hello. I think the best way is to learn from this file.

Maybe, at least knowing from the error message, you need to apt-get pkg-config and libfuse-dev. And if you are in the test dir, you should add -p to add the top directory to Nim's search path (see .travis.yml).

**Comment by YafahEdelman** [comment]
Yup! That worked. You may want to add something about what is needed to set it up in the readme and maybe add an install script.
